version: "2"
services:
  gibbon:
    depends_on:
      - db
    image: kerrongordon/gibbon
    restart: on-failure
    ports:
      - 80:80
    networks:
      - overlay
  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ASb23123908ASDklKMSAD
      MYSQL_DATABASE: svimsdb
    networks:
      - overlay

networks:
  overlay:
volumes:
  data:
